### ISSUE TITLE
使用谷歌地图切片是否需要license？

### ISSUE THREAD

**Issue by alex2wong** [MapTalks/raster-collection#1]
hi Zhen,
  如果把谷歌地图切片源用在企业售卖的web app 里（通过leaflet这类开源api去加载），是否要去谷歌申请使用权，付费使用？
我看到有个谷歌的文档，如下：
https://enterprise.google.com/maps/terms/us/maps_purchase_agreement.html
然后有一个 google product 论坛的帖子https://productforums.google.com/forum/#!topic/maps/6AE2uNhuMtw，感觉好混乱。。

不知道你们有没有企业产品需要用到google 底图的经验？

**Comment by fuzhenn** [comment]
hmm... 这个问题我也不是十分清楚，生产环境里没怎么用到过互联网底图。
可以试试直接联系google的商务

**Comment by alex2wong** [comment]
ok, 谢谢 : )
